# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='Not Reviewed', max_length=14),
        ),
    ]
